import React from "react"
import Layout from "../../components/layout"

const Collections = ({}) => (
  <Layout>
    <div className="row u__no_margin u__100vh white_color">
      <div className="col-xl-12 u__no_padding">
        <h1>COLLECTIONS</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
        <h1>collection</h1>
      </div>
    </div>
  </Layout>
)

export default Collections
